spring.application.name=be
# Thông tin k?t n?i Database
spring.datasource.url=jdbc:postgresql://localhost:5432/tsmarthome_db
spring.datasource.username=postgres
spring.datasource.password=mat_khau_cua_ban
spring.datasource.driver-class-name=org.postgresql.Driver

# C?u hình Hibernate / JPA
# Vì b?n ?ã có file SQL t?o b?ng s?n, ta dùng 'validate' ho?c 'none' ?? Spring Boot không t? t?o l?i/xóa b?ng
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# C?u hình Server Port (Tùy ch?n, m?c ??nh là 8080)
server.port=8080