spring.application.name=be
spring.datasource.url=jdbc:postgresql://localhost:5432/tsmarthome_db
spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
server.address=0.0.0.0
server.port=8080
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hantrungcui@gmail.com
spring.mail.password=anhz yisp alxx cumm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mqtt.broker.url=tcp://broker.emqx.io:1883
mqtt.client.id=tsmarthome-backend-server
gemini.api.key=AQ.Ab8RN6K4epVgHOlSA_jHnLygEVrczC1BKRgsqy8tF4CW8iC0pQ
gemini.model=gemini-3.5-flash

# Cloudinary Config
cloudinary.cloud-name=db4pvjuup
cloudinary.api-key=973186148427996
cloudinary.api-secret=goRR_6zAuDVKa08Cp89EXy6QuK8

# JWT Config
jwt.secret=TSmartHome2026SecureJwtSecretKey!!TSmartHome2026SecureJwtSecretKey!!
jwt.expiration=86400000
