spring.application.name=be
# Thông tin k?t n?i Database
spring.datasource.url=jdbc:postgresql://localhost:5432/tsmarthome_db
spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver

# C?u hình Hibernate / JPA
# Vì b?n ?ã có file SQL t?o b?ng s?n, ta dùng 'validate' ho?c 'none' ?? Spring Boot không t? t?o l?i/xóa b?ng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.address=0.0.0.0
# C?u hình Server Port (Tùy ch?n, m?c ??nh là 8080)
server.port=8080

# C?u hình Email (Dùng Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hantrungcui@gmail.com
# L?u ý: ?ây là M?t kh?u ?ng d?ng (App Password) c?a Gmail, không ph?i m?t kh?u ??ng nh?p!
spring.mail.password=anhz yisp alxx cumm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# C?U HÌNH MQTT (Kh?p v?i ESP32)
# ===============================
mqtt.broker.url=tcp://broker.emqx.io:1883

# L?U Ý QUAN TR?NG: Client ID c?a Backend PH?I KHÁC v?i c?a ESP32
# N?u ??t trùng nhau, 2 bên s? liên t?c "?á" nhau v?ng kh?i server
mqtt.client.id=tsmarthome-backend-server

# Vì broker public c?a EMQX không yêu c?u user/pass nên ta comment l?i ho?c xóa ?i
# mqtt.username=
# mqtt.password=
gemini.api.key=AIzaSyDFazfo_4wtJ6xnJ1btnXxwtDn0nUQIupE
gemini.model=gemini-3.5-flash